name: store_dashboard
description: A polished Flutter dashboard for professional store management.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
